import {StyleSheet, Dimensions} from 'react-native';

const {width} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    height: 140,
    backgroundColor: 'white',
    elevation: 5,
  },
  header: {
    width,
    display: 'flex',
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 20,
    paddingRight: 20,
    marginBottom: 5,
  },
  headerText: {
    textAlign: 'left',
    color: 'black',
    textAlignVertical: 'center',
    height: '100%',
    fontWeight: 'bold',
    fontSize: 24,
  },
  imageContainer: {
    width: 28,
    height: 28,
    alignSelf: 'center',
    // backgroundColor: 'red',
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  buttonSmall: {
    height: 28,
    width: 90,
    backgroundColor: '#F7F7F9',
    borderWidth: 0.8,
    borderColor: '#E6E6E8',
    borderRadius: 3,
    marginTop: 12,
    marginLeft: 5,
    marginRight: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  buttonLarge: {
    height: 28,
    width: 120,
    backgroundColor: '#F7F7F9',
    borderWidth: 0.8,
    borderColor: '#E6E6E8',
    borderRadius: 3,
    marginTop: 12,
    marginLeft: 5,
    marginRight: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  buttonSmallSelected: {
    height: 28,
    width: 90,
    borderWidth: 0.8,
    borderColor: '#AB84C8',
    backgroundColor: '#AB84C8',
    elevation: 3,
    borderRadius: 3,
    marginTop: 12,
    marginLeft: 5,
    marginRight: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  buttonLargeSelected: {
    height: 28,
    width: 120,
    borderWidth: 0.8,
    borderColor: '#AB84C8',
    backgroundColor: '#AB84C8',
    elevation: 3,
    borderRadius: 3,
    marginTop: 12,
    marginLeft: 5,
    marginRight: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  buttonTextSelected: {
    fontWeight: 'normal',
    fontSize: 14,
    textAlign: 'center',
    color: 'white',
    paddingTop: 3,
  },
  buttonText: {
    fontWeight: 'normal',
    fontSize: 14,
    textAlign: 'center',
    color: 'black',
    paddingTop: 3,
  },
  iconStyle: {width: 14, height: 14, alignSelf: 'center', resizeMode: 'cover'},
});

export default styles;
